name: Deploy-Server
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Web
        run: |
          cd web
          yarn
          yarn build
      
      - name: Build App
        run: |
          yarn
      
      - name: Deploy
        run: now -c --token ${{secrets.ZEIT_TOKEN}}